version: '3.5'

services:
  janus-gateway:
    build: .
    ports:
      - 80:80
      - 443:443
      - 7088:7088
      - 8088:8088
      - 8188:8188
      - 8089:8089
    environment:
      - DOCKER_IP=${DOCKER_IP}
